// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYYBM5qPiSE4d1Dw9NjPmpk97p8KGnAA',
    appId: '1:1034128774527:web:02f1baf596421e9dc3b64a',
    messagingSenderId: '1034128774527',
    projectId: 'nummofi',
    authDomain: 'nummofi.firebaseapp.com',
    storageBucket: 'nummofi.firebasestorage.app',
    measurementId: 'G-0H0XN1LSDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9j8Qb_EiDQF6rN7Y-6zNi3II7Jpy4qpU',
    appId: '1:1034128774527:android:315e739d3c131c80c3b64a',
    messagingSenderId: '1034128774527',
    projectId: 'nummofi',
    storageBucket: 'nummofi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFpNz7jyNL2t11ELLRrCloekoUQye8d4',
    appId: '1:1034128774527:ios:1388b2cd4e171c40c3b64a',
    messagingSenderId: '1034128774527',
    projectId: 'nummofi',
    storageBucket: 'nummofi.firebasestorage.app',
    iosBundleId: 'com.example.nummofi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGFpNz7jyNL2t11ELLRrCloekoUQye8d4',
    appId: '1:1034128774527:ios:1388b2cd4e171c40c3b64a',
    messagingSenderId: '1034128774527',
    projectId: 'nummofi',
    storageBucket: 'nummofi.firebasestorage.app',
    iosBundleId: 'com.example.nummofi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNYYBM5qPiSE4d1Dw9NjPmpk97p8KGnAA',
    appId: '1:1034128774527:web:6f8a4c7b0cd3d0e6c3b64a',
    messagingSenderId: '1034128774527',
    projectId: 'nummofi',
    authDomain: 'nummofi.firebaseapp.com',
    storageBucket: 'nummofi.firebasestorage.app',
    measurementId: 'G-6CCV0MEFYD',
  );
}
